# https://help.github.com/en/articles/metadata-syntax-for-github-actions
name: 'Docker Login'
description: 'GitHub Action to login against a Docker registry'
author: 'docker'
branding:
  icon: 'anchor'
  color: 'blue'

inputs:
  registry:
    description: 'Server address of Docker registry. If not set then will default to Docker Hub'
    required: false
  username:
    description: 'Username used to log against the Docker registry'
    required: false
  password:
    description: 'Password or personal access token used to log against the Docker registry'
    required: false
  ecr:
    description: 'Specifies whether the given registry is ECR (auto, true or false)'
    default: 'auto'
    required: false
  logout:
    description: 'Log out from the Docker registry at the end of a job'
    default: 'true'
    required: false
  http-codes-to-retry:
    description: 'Comma separated list of HTTP error codes we want to retry'
    default: '408,500,502,504'
  max-attempts:
    description: 'Overall maximum number of attempts we will make trying to login'
    default: '1'
    required: false
  retry-timeout:
    description: 'Timeout between retries, in seconds'
    default: '15'
    required: false

runs:
  using: 'node20'
  main: 'dist/index.js'
  post: 'dist/index.js'
